---
- name: AWX에서 로컬 manager에게 docker-swarm 명령 보내기
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: web 서비스 배포하기
      docker_swarm_service:
        name: myweb
        image: andrewyss/rapaeng4:blue
        placement:
          constraints:
            - node.role == worker
        replicas: 3
        reservations:
          cpus: "0.5"
          memory: "50M"
        limits:
          cpus: "1.0"
          memory: "100M"
        endpoint_spec:
          mode: vip
          ports:
            - target_port: 80
              published_port: 8008
        

